### PR TITLE
can you not share your shit with everyone else

### PR DESCRIPTION
**Pull request by ItzSwirlz**
also why tf are you not using a .gitignore or eclipse

### CODE REVIEW

**Comment by Arti-Dev** [comment]
I mean IntelliJ is a viable option

**Comment by ChachyDev** [comment]
Intellij is fine, not using a gitignore is ....

**Comment by ItzSwirlz** [comment]
yeah tbh intellij is fine. It's not terrible, Android Studio is made with intellij and is also for Java devel. For MC I just prefer eclipse but /shrug (he's also using Maven not Gradle)

**Comment by ItzSwirlz** [comment]
Okay for real this is done on live stream and Minikloon wants to be serious.

**Pull request closed without merging**
